server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:8097,localhost:8098,localhost:8099
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 180200
    driver-class-name: org.postgresql.Driver